### ISSUE TITLE
question about ours-1q and ours-2q?

### ISSUE THREAD

**Issue by MrChenFeng** [UMBCvision/CompRess#3]
Thanks for sharing your code!
I wonder is train_student.py corresponds to ours-1q while train_student_without_momentum.py corresponds to ours-2q?
The second file is reasonable with the detached momentum encoder and the queue been updated with feats from this encoder.
However, I found in the first file, the student encoder will contrast to the previous samples' representation of itself rather than the teacher encoder, which is not clear to me.
Appreciate for you reply!

**Comment by ajtejankar** [comment]
Hi,

Sorry, we forgot to add the code for ours-1q. I just added a file named `train_student_one_queue.py`. 

Thanks

**Comment by JindongGu** [comment]
> Hi,
> 
> Sorry, we forgot to add the code for ours-1q. I just added a file named `train_student_one_queue.py`.
> 
> Thanks

Thanks for sharing your code!

The file train_student_one_queue.py differs from train_student.py only in the compress loss, right?
CompReSSA vs. CompReSSMomentum

Other hyper-parameters stay the same?

 Thanks for your reply in advance!

**Comment by ajtejankar** [comment]
Hi,

Actually, there are two differences. First, the loss, as you correctly pointed out, and second, an additional [linear layer](https://github.com/UMBCvision/CompRess/blob/master/train_student_one_queue.py#L171) to match the dimension of the student to the teacher. In the 2-q version, both student and the teacher have their own anchor points/memory bank/queue so you are always taking a dot product with the embeddings of the same dimension. While in the 1-q version, the student and teacher embeddings can have different dimensions. Thus, we use a linear layer to project the student embeddings into the teacher's embedding space.

Thanks a lot for your interest in our work. :)
