### ISSUE TITLE
MobileNet v2 weight

### ISSUE THREAD

**Issue by dev-sungman** [UMBCvision/CompRess#4]
Hi, 

Thank you for sharing code and pretrained weight.

Can I ask you to share pretrained MobileNet v2 (MoCo v2) weight ? 

I want to compare MobileNet v2 (MoCo v2 pretrained) with MobileNet v2 (Compress w/ MoCo ResNet-50).

Thank you.

**Comment by ajtejankar** [comment]
Hi @dev-sungman,

Sure. Here's a link to the MobileNet-v2 model pretrained with MoCo-v2 for 200 epochs:

https://drive.google.com/file/d/19iMue4wlU8QtfDMpnN7b2KaPcxHgKDFx/view?usp=sharing

Thanks
